services:
  database:
    image: 'postgres:18.4'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: labpro
      POSTGRES_DB: labpro
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: pg_isready -U admin -d labpro || exit 1
    restart: always

  cache:
    image: 'redis:7.4.10'
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli ping || exit 1
    restart: always

volumes:
  postgres_data:
  redis_data:
