# Generated by Django 5.1 on 2024-08-19 05:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('director', models.CharField(max_length=256)),
                ('release_year', models.IntegerField()),
                ('genre', models.TextField(default='[]')),
                ('price', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('video', models.FileField(upload_to='videos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
            ],
        ),
    ]
