# Generated by Django 5.1 on 2024-08-19 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0002_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='film',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
