# Generated by Django 5.1 on 2024-08-19 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0003_film_created_at_film_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
