# Generated by Django 5.1 on 2024-08-20 23:35

import be.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0004_alter_film_created_at_alter_film_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=be.models.Film.cover_image_filename_renamer),
        ),
        migrations.AlterField(
            model_name='film',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='video',
            field=models.FileField(upload_to=be.models.Film.video_filename_renamer),
        ),
    ]
