# Generated by Django 5.1 on 2024-08-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0008_alter_profile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bought_movies',
            field=models.TextField(default='[]'),
        ),
    ]
