"""
Django settings for labpro project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv()


def env_str(name, default=None):
    value = os.getenv(name)
    return value if value not in (None, "") else default


def env_bool(name, default=False):
    value = env_str(name)
    if value is None:
        return default
    return value.strip().lower() in ("1", "true", "yes", "on")


def env_int(name, default):
    value = env_str(name)
    return int(value) if value is not None else default


def env_list(name, default=None):
    value = env_str(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_str("SECRET_KEY")

# JWT
ACCESS_TOKEN_SECRET = env_str("ACCESS_TOKEN_SECRET")
JWT_ALGORITHM = env_str("JWT_ALGORITHM", "HS256")

LOGIN_REDIRECT_URL = env_str("LOGIN_REDIRECT_URL", "/")
LOGOUT_REDIRECT_URL = env_str("LOGOUT_REDIRECT_URL", "/")

# Email
EMAIL_BACKEND = env_str("EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = env_str("EMAIL_HOST")
EMAIL_PORT = env_int("EMAIL_PORT", 25)
EMAIL_USE_SSL = env_bool("EMAIL_USE_SSL")
EMAIL_HOST_USER = env_str("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env_str("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = env_str("DEFAULT_FROM_EMAIL", "webmaster@localhost")

# Logging
# Django only configures the 'django' logger by default; application loggers
# fall back to the root logger, which has no handler and therefore drops
# anything below WARNING. Send both to stderr so gunicorn captures them.
LOG_LEVEL = env_str("LOG_LEVEL", "INFO").upper()

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{asctime} {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": LOG_LEVEL,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DEBUG")

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", ["*"])
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS")

# Virtual host routing (see labpro/hosts.py)
BACKEND_HOSTS = env_list("BACKEND_HOSTS", ["labpro.local"])
API_HOSTS = env_list("API_HOSTS", ["api.labpro.local", "localhost"])
VIRTUAL_HOST_PORTS = env_list("VIRTUAL_HOST_PORTS", ["8000"])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'labpro',
    'api',
    'be',
]

MIDDLEWARE = [
    'labpro.hosts.VirtualHostMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'labpro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'fe'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'labpro.context_processors.api_host',
            ],
        },
    },
]

WSGI_APPLICATION = 'labpro.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'ENGINE': env_str("DATABASES_ENGINE", "django.db.backends.postgresql"),
        'NAME': env_str("DATABASES_NAME"),
        'USER': env_str("DATABASES_USER"),
        'PASSWORD': env_str("DATABASES_PASSWORD"),
        'HOST': env_str("DATABASES_HOST"),
        'PORT': env_str("DATABASES_PORT"),
    }
}

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": env_str("REDIS_URL", "redis://localhost:6379/"),
    }
}
CACHE_DEFAULT_TIMEOUT = env_int("CACHE_DEFAULT_TIMEOUT", 2700)

CLOUDFLARE_R2_BUCKET=env_str("CLOUDFLARE_R2_BUCKET")
CLOUDFLARE_R2_BUCKET_ENDPOINT=env_str("CLOUDFLARE_R2_BUCKET_ENDPOINT")
CLOUDFLARE_R2_ACCESS_KEY=env_str("CLOUDFLARE_R2_ACCESS_KEY")
CLOUDFLARE_R2_SECRET_KEY=env_str("CLOUDFLARE_R2_SECRET_KEY")
# Public hostname serving the bucket (no scheme, no trailing slash).
# Object URLs are built from this instead of the default *.r2.dev endpoint.
CLOUDFLARE_R2_CUSTOM_DOMAIN=env_str("CLOUDFLARE_R2_CUSTOM_DOMAIN", "labproflix-cdn.faizath.com")

CLOUDFLARE_R2_CONFIG_OPTIONS = {
    "bucket_name": CLOUDFLARE_R2_BUCKET,
    "default_acl": "public-read",  # or "private"
    "signature_version": "s3v4",
    "endpoint_url": CLOUDFLARE_R2_BUCKET_ENDPOINT,
    "access_key": CLOUDFLARE_R2_ACCESS_KEY,
    "secret_key": CLOUDFLARE_R2_SECRET_KEY,
    "custom_domain": CLOUDFLARE_R2_CUSTOM_DOMAIN,
    "url_protocol": "https:",
    "querystring_auth": False,
}

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": CLOUDFLARE_R2_CONFIG_OPTIONS,
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

#SITE_ROOT = os.path.dirname(os.path.realpath(__file__))
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'fe/static')
]
# Must stay outside fe/, which is also the template directory: with
# STATIC_ROOT = fe/, collectstatic copied fe/static/browse.html straight over
# the fe/browse.html template.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'be.Profile'

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.ScryptPasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = env_str("LANGUAGE_CODE", "en-us")

TIME_ZONE = env_str("TIME_ZONE", "UTC")

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
